---
# Playbook qui permet d'installer la commande htop
# Installation sur tous les serveur
#
- hosts: all

  user: administrateur
  sudo: yes

  tasks:
    - name:   Installation de htop
      action: apt name=htop state=installed
      tags:   htop
